### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by paulomcnally** [danhol86/dh-messages-api#1]
Hi, have examples to use?

**Comment by danhol86** [comment]
Check out https://github.com/danhol86/dh-messages-api/blob/master/build/test.js
Not looked at this for over a year, so not sure if still works....

**Comment by danhol86** [comment]
> Hi, have examples to use?

Was a couple of bugs, which hacked to get to work now. If call 'npm run start' then should now generate the qr code link and the test will generate a new QR code image in the folder. Once this has done, comment out New() in test.ts and can use the Existing();

**Comment by danhol86** [comment]
Examples now added with docker
